language: java

jdk:
  - oraclejdk8
  - openjdk7
 
stages:
  - test
  - name: startFeature
    if: env(startFeature) = true
  - name: finishFeature
    if: env(finishFeature) = true
  - name: deploySnapshot
    if: branch = develop
  - name: deployRelease
    if: env(manualDeploy) = true
    
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
      
install: mvn --settings .travis/settings.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: skip

jobs:
  include:
    - stage: deploySnapshot
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-httprequestlibrary
          branch: develop
          jdk: oraclejdk8
    - stage: deployRelease
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-httprequestlibrary
          jdk: oraclejdk8
    - stage: startRelease
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-httprequestlibrary
          jdk: oraclejdk8
    - stage: finishRelease
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-httprequestlibrary
          jdk: oraclejdk8